language: python
install:
- pip install -e .
matrix:
  include:
  - python: 3.6
  - python: 3.7
  - python: 3.8
  - python: 3.9
script:
  - coverage run --concurrency=multiprocessing -m unittest discover tests/
  - coverage combine
after_success:
  - coveralls
notifications:
  email: false