executable = /data/user/gsommani/alertstack-icecube/examples/flaires_neutrino_alert/run_flaires_analysis.sh
arguments =  --n_trials 100 --fraction 0.07 --n_steps 10 --tag flaires_n100_f0.07_s10_N$(i)
log = flaires_n100_f0.07_s10_N$(i).log
output = flaires_n100_f0.07_s10_N$(i).out
error = flaires_n100_f0.07_s10_N$(i).err
request_cpus = 4
request_memory = 16GB
request_disk = 32GB
should_transfer_files = yes

queue