executable = /data/user/gsommani/alertstack-icecube/examples/sjoert_accretion_flares_neutrino_alert/run_sjoert_analysis.sh
arguments =  --n_trials 1000 --fraction 0.25 --n_steps 15 --tag sjoert_n1000_f0.25_s15_N$(i)
log = sjoert_n1000_f0.25_s15_N$(i).log
output = sjoert_n1000_f0.25_s15_N$(i).out
error = sjoert_n1000_f0.25_s15_N$(i).err
request_cpus = 4
request_memory = 16GB
request_disk = 32GB
should_transfer_files = yes

queue